//go:build integration

package txm

import (
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"math/big"
	"path/filepath"
	"testing"
	"time"

	"github.com/aptos-labs/aptos-go-sdk"
	aptosapi "github.com/aptos-labs/aptos-go-sdk/api"
	"github.com/aptos-labs/aptos-go-sdk/bcs"
	aptoscrypto "github.com/aptos-labs/aptos-go-sdk/crypto"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/go-viper/mapstructure/v2"
	"github.com/google/uuid"
	"github.com/stretchr/testify/require"
	"golang.org/x/crypto/sha3"

	"github.com/smartcontractkit/chainlink-common/pkg/logger"
	"github.com/smartcontractkit/chainlink-common/pkg/loop"

	"github.com/smartcontractkit/chainlink-aptos/relayer/ratelimit"
	"github.com/smartcontractkit/chainlink-aptos/relayer/testutils"
	"github.com/smartcontractkit/chainlink-aptos/relayer/types"
	"github.com/smartcontractkit/chainlink-aptos/relayer/utils"
)

type Account struct {
	privateKey     ed25519.PrivateKey
	publicKey      ed25519.PublicKey
	accountAddress aptos.AccountAddress
}

var (
	client      *aptos.NodeClient
	mcmsAccount aptos.AccountAddress
	mcmsAddress string
	chainIdBig  *big.Int
	nextNonce   uint64 = 0
	postOpCount uint64 = 0
	preOpCount  uint64 = 0
)

func getNextNonce() uint64 {
	nonce := nextNonce
	nextNonce++
	return nonce
}

func getPreOpCount() uint64 {
	return postOpCount
}

func getCumulativePostOpCount(numOps uint64) uint64 {
	postOpCount += numOps
	return postOpCount
}

func TestMultisigLocal(t *testing.T) {
	logger := logger.Test(t)

	accounts := []Account{}
	keystore := testutils.NewTestKeystore(t)

	for i := 0; i < 5; i++ {
		var account Account
		if i == 0 {
			privateKey, publicKey, accountAddress := testutils.LoadAccountFromEnv(t, logger)
			if privateKey != nil {
				logger.Debugw("Loaded account", "publicKey", hex.EncodeToString([]byte(publicKey)), "accountAddress", accountAddress.String())
				account = Account{privateKey, publicKey, accountAddress}
			}
		}
		if account.privateKey == nil {
			publicKey, privateKey, err := ed25519.GenerateKey(rand.Reader)
			require.NoError(t, err)

			authKey := sha3.Sum256(append([]byte(publicKey), 0x00))
			accountAddress := aptos.AccountAddress(authKey)

			logger.Debugw("Created account", "publicKey", hex.EncodeToString([]byte(publicKey)), "accountAddress", accountAddress.String())
			logger.Debugw("Loaded private key", "privateKey", hex.EncodeToString([]byte(privateKey)))
			account = Account{privateKey, publicKey, accountAddress}
		}
		accounts = append(accounts, account)
		keystore.AddKey(account.privateKey)
	}

	err := testutils.StartAptosNode()
	require.NoError(t, err)
	logger.Debugw("Started Aptos node")

	rpcUrl := "http://localhost:8080/v1"
	client, err := aptos.NewNodeClient(rpcUrl, 0)
	require.NoError(t, err)

	faucetUrl := "http://localhost:8081"
	for _, account := range accounts {
		err = testutils.FundWithFaucet(logger, client, account.accountAddress, faucetUrl)
		require.NoError(t, err)
	}

	runMultisigTest(t, logger, rpcUrl, keystore, accounts, false)
}

func runMultisigTest(t *testing.T, logger logger.Logger, rpcURL string, keystore loop.Keystore, accounts []Account, skipEOATest bool) {
	// Generate bypasser and proposer signers
	bypasserSigners := GenerateSigners(t, 3)
	proposerSigners := GenerateSigners(t, 3)
	// Log generated signers
	for _, signer := range bypasserSigners {
		logger.Debugw("Generated bypasser signer", "address", hex.EncodeToString(signer.Address))
	}
	for _, signer := range proposerSigners {
		logger.Debugw("Generated proposer signer", "address", hex.EncodeToString(signer.Address))
	}

	deployer := accounts[0]
	deployerAddress := deployer.accountAddress.String()
	deployerPublicKeyHex := hex.EncodeToString([]byte(deployer.publicKey))

	// Use a random seed so it doesn't fail if we test repeatedly on testnet
	mcmsSeed := make([]byte, 64)
	_, err := rand.Read(mcmsSeed)
	require.NoError(t, err)

	mcmsAccount = deployer.accountAddress.ResourceAccount(mcmsSeed)
	mcmsAddress = mcmsAccount.String()

	logger.Debugw("MCMS resource account", "address", mcmsAddress)

	mcmsPackageMetadataBytes, mcmsModuleBytecodeBytes := compileMcmsContract(t, mcmsAccount, deployer.accountAddress)

	client, err := aptos.NewNodeClient(rpcURL, 0)
	require.NoError(t, err)

	chainInfo := types.ChainInfo{
		ChainFamilyName: "aptos",
		ChainID:         "3",
		NetworkName:     "testnet",
	}
	rlClient := ratelimit.NewRateLimitedClient(client, chainInfo, rpcURL, 100, 30*time.Second)
	getClient := func() (aptos.AptosRpcClient, error) {
		return rlClient, nil
	}

	chainId, err := client.GetChainId()
	require.NoError(t, err)
	chainIdBig = new(big.Int).SetUint64(uint64(chainId))

	config := DefaultConfigSet
	txm, err := New(logger, keystore, config, getClient, chainInfo.ChainID)
	require.NoError(t, err)
	err = txm.Start(context.Background())
	require.NoError(t, err)

	// deploy mcms module
	deployId := uuid.New().String()
	err = txm.Enqueue(
		deployId,
		GetSampleTxMetadata(),
		deployerAddress,
		deployerPublicKeyHex,
		"0x1::resource_account::create_resource_account_and_publish_package",
		/* typeArgs= */ []string{},
		/* paramTypes= */ []string{"vector<u8>", "vector<u8>", "vector<vector<u8>>"},
		/* paramValues= */ []any{mcmsSeed, mcmsPackageMetadataBytes, mcmsModuleBytecodeBytes},
		/* simulateTx= */ false,
	)
	require.NoError(t, err)
	WaitForTxmId(t, txm, deployId, time.Second*30)

	logger.Infow("published module", "deployerAddress", deployerAddress, "mcmsAddress", mcmsAddress)

	// Wait for the multisig to be initialized
	{
		pollEndTime := time.Now().Add(time.Second * 3)
		var resource map[string]any
		for time.Now().Before(pollEndTime) {
			resource, err = client.AccountResource(mcmsAccount, mcmsAddress+"::mcms::MultisigState")
			if err != nil {
				time.Sleep(time.Second * 1)
				continue
			}
			logger.Debugw("Got resource", "resource", resource)
			break
		}
		require.NotNil(t, resource)

		pollEndTime = time.Now().Add(time.Second * 3)
		for time.Now().Before(pollEndTime) {
			resource, err = client.AccountResource(mcmsAccount, mcmsAddress+"::mcms::Timelock")
			if err != nil {
				time.Sleep(time.Second * 1)
				continue
			}
			logger.Debugw("Got resource", "resource", resource)
			break
		}
		require.NotNil(t, resource)
	}

	// Call set_config to set signers
	role := uint8(PROPOSER_ROLE)
	SetupInitialConfigAsDeployer(t, logger, txm, uint8(BYPASSER_ROLE), bypasserSigners, deployerAddress, deployerPublicKeyHex, false, mcmsAddress, false)
	// Setup role for Proposer too
	SetupInitialConfigAsDeployer(t, logger, txm, role, proposerSigners, deployerAddress, deployerPublicKeyHex, false, mcmsAddress, false)

	functionOneArg1 := "hello"
	functionOneArg2 := []byte{5, 4, 3, 2, 1}
	functionTwoArg1 := deployer.accountAddress[:]
	functionTwoArg2 := big.NewInt(42)

	// function_one(arg1: String, arg2: vector<u8>)
	functionOneParamBytes := GetFunctionOneParamBytes(t, functionOneArg1, functionOneArg2)

	// function_two(arg1: address, arg2: u128)
	functionTwoParamBytes := GetFunctionTwoParamBytes(t, functionTwoArg1, functionTwoArg2)

	t.Run("TransferOwnershipAndExecuteMCMSDeployedUserContract", func(t *testing.T) {
		role := uint8(PROPOSER_ROLE)
		TransferOwnership(t, txm, deployerAddress, deployerPublicKeyHex, mcmsAddress, false)

		newOwnerSeed := []byte("mcms_user_contract")
		codeObjectOwnerAccount := mcmsAccount.ResourceAccount(append([]byte("CHAINLINK_MCMS_NEW_OBJECT_REGISTRATION"), newOwnerSeed...))

		objectCodeDeploymentSeparator := []byte("aptos_framework::object_code_deployment")
		objectCodeDeploymentSeparatorBytes, err := bcs.SerializeSingle(func(ser *bcs.Serializer) {
			ser.WriteBytes(objectCodeDeploymentSeparator)
		})
		require.NoError(t, err)
		sequenceOneBytes, err := bcs.SerializeSingle(func(ser *bcs.Serializer) {
			ser.U64(1)
		})
		require.NoError(t, err)

		userModuleAccount := codeObjectOwnerAccount.NamedObjectAddress(append(objectCodeDeploymentSeparatorBytes, sequenceOneBytes...))

		logger.Debugw("Preregistered user module account", "owner address", codeObjectOwnerAccount.String(), "code object address", userModuleAccount.String())

		mcmsUserPackageMetadataBytes, mcmsUserModuleBytecodeBytes := compileMcmsUserContract(t, userModuleAccount, mcmsAccount)

		stageCodeChunkAndPublishToAccountBytes, err := bcs.SerializeSingle(func(ser *bcs.Serializer) {
			ser.WriteBytes(mcmsUserPackageMetadataBytes)

			// code_indices = [0]
			ser.Uleb128(1)
			ser.U16(0)

			// code_chunks = [user module bytecode]
			ser.Uleb128(1)
			ser.WriteBytes(mcmsUserModuleBytecodeBytes)

			// new owner seed
			ser.WriteBytes(newOwnerSeed)
		})

		// First schedule the timelock operations
		scheduleTimelockOps := []TimelockOperation{
			{
				Target:       mcmsAccount,
				ModuleName:   "mcms_account",
				FunctionName: "accept_ownership",
				Data:         []byte{},
			},
			{
				Target:       mcmsAccount,
				ModuleName:   "mcms_deployer",
				FunctionName: "stage_code_chunk_and_publish_to_object",
				Data:         stageCodeChunkAndPublishToAccountBytes,
			},
			{
				Target:       userModuleAccount,
				ModuleName:   "mcms_user",
				FunctionName: "function_one",
				Data:         functionOneParamBytes,
			},
			{
				Target:       userModuleAccount,
				ModuleName:   "mcms_user",
				FunctionName: "function_two",
				Data:         functionTwoParamBytes,
			},
		}
		// ZERO_HASH (32 bytes of zeros)
		predecessor := make([]byte, 32)
		salt := []byte{}
		delay := uint64(0)

		rootMetadata := RootMetadata{
			Role:                 role,
			ChainID:              chainIdBig,
			MultiSig:             mcmsAccount,
			PreOpCount:           getPreOpCount(),
			PostOpCount:          getCumulativePostOpCount(uint64(len(scheduleTimelockOps))), // We execute each op individually
			OverridePreviousRoot: false,
		}

		ops := TimelockOpToMultipleOps(scheduleTimelockOps, predecessor, salt, delay, role, chainIdBig, mcmsAccount, getNextNonce)

		// Log hashRootMetadata and contents
		metadataHash, err := HashRootMetadata(rootMetadata)
		require.NoError(t, err)
		logger.Debugw("hashRootMetadata", "value", hex.EncodeToString(metadataHash[:]))
		logger.Debugw("ops", "value", ops)

		merkleTree, err := GenerateMerkleTree(ops, rootMetadata)
		require.NoError(t, err)

		setRootId := EnqueueSetRoot(t, logger, merkleTree, txm, rootMetadata, proposerSigners, deployerAddress, deployerPublicKeyHex, mcmsAddress)
		WaitForTxmId(t, txm, setRootId, time.Second*30)

		// Schedule operations through MCMS -> MCMS Timelock
		for i, op := range scheduleTimelockOps {
			proof := merkleTree.GetProof(i + 1)
			hashOp, err := HashOp(&ops[i])
			require.NoError(t, err)
			require.True(t, merkleTree.VerifyProof(proof, hashOp))
			txId := ScheduleSingleOperationAsDeployer(t, logger, txm, mcmsAccount, deployerAddress, deployerPublicKeyHex,
				[]TimelockOperation{op}, predecessor, salt, delay, role, chainIdBig, ops[i].Nonce, proof, false)
			WaitForTxmId(t, txm, txId, time.Second*30)
		}

		// Wait for timelock delay
		time.Sleep(time.Duration(TEST_DELAY) * time.Second)

		// Execute initial operations through timelock
		executeTimelockOps := []TimelockOperation{
			{
				Target:       mcmsAccount,
				ModuleName:   "mcms_account",
				FunctionName: "accept_ownership",
				Data:         []byte{},
			},
			{
				Target:       mcmsAccount,
				ModuleName:   "mcms_deployer",
				FunctionName: "stage_code_chunk_and_publish_to_object",
				Data:         stageCodeChunkAndPublishToAccountBytes,
			},
			{
				Target:       userModuleAccount,
				ModuleName:   "mcms_user",
				FunctionName: "function_one",
				Data:         functionOneParamBytes,
			},
			{
				Target:       userModuleAccount,
				ModuleName:   "mcms_user",
				FunctionName: "function_two",
				Data:         functionTwoParamBytes,
			},
		}

		// Here we execute each op one by one, to prevent EXECUTION_LIMIT_REACHED
		for i := 0; i < len(executeTimelockOps); i++ {
			txId := ExecuteBatchOperations(t, txm, mcmsAddress, deployerAddress, deployerPublicKeyHex,
				[]TimelockOperation{executeTimelockOps[i]}, predecessor, salt, false)
			WaitForTxmId(t, txm, txId, time.Second*30)
		}

		// Verify final state
		{
			pollEndTime := time.Now().Add(time.Second * 30)
			var resource map[string]any
			for time.Now().Before(pollEndTime) {
				resource, err = client.AccountResource(userModuleAccount, userModuleAccount.String()+"::mcms_user::UserData")
				if err != nil {
					time.Sleep(time.Second * 1)
					continue
				}
				logger.Debugw("Got resource", "resource", resource)
				break
			}
			require.NotNil(t, resource)

			var result struct {
				Data struct {
					Invocations int
					A           string
					B           string
					C           string
					D           string
				}
			}
			err = mapstructure.Decode(resource, &result)
			require.NoError(t, err)

			require.Equal(t, result.Data.A, functionOneArg1)

			bBytes, err := utils.DecodeHexRelaxed(result.Data.B)
			require.NoError(t, err)
			require.Equal(t, bBytes, functionOneArg2)

			cBytes, err := utils.DecodeHexRelaxed(result.Data.C)
			require.NoError(t, err)
			require.Equal(t, cBytes, functionTwoArg1)

			dInt, ok := new(big.Int).SetString(result.Data.D, 10)
			require.True(t, ok)
			require.Equal(t, dInt, functionTwoArg2)
		}
	})

	if skipEOATest {
		t.Run("ExecuteEOADeployedUserContract", func(t *testing.T) {
			role := uint8(PROPOSER_ROLE)
			mcmsUserDeployer := accounts[1]
			mcmsUserDeployerAddress := mcmsUserDeployer.accountAddress.String()
			mcmsUserDeployerPublicKeyHex := hex.EncodeToString([]byte(mcmsUserDeployer.publicKey))

			mcmsUserPackageMetadataBytes, mcmsUserModuleBytecodeBytes := compileMcmsUserContract(t, mcmsUserDeployer.accountAddress, mcmsAccount)

			// deploy and initialize mcms user module
			err = txm.Enqueue(
				uuid.New().String(),
				GetSampleTxMetadata(),
				mcmsUserDeployerAddress,
				mcmsUserDeployerPublicKeyHex,
				"0x1::code::publish_package_txn",
				/* typeArgs= */ []string{},
				/* paramTypes= */ []string{"vector<u8>", "vector<vector<u8>>"},
				/* paramValues= */ []any{mcmsUserPackageMetadataBytes, [][]byte{mcmsUserModuleBytecodeBytes}},
				/* simulateTx= */ true,
			)
			require.NoError(t, err)

			// Wait for the user contract to be initialized
			{
				pollEndTime := time.Now().Add(time.Second * 30)
				var resource map[string]any
				for time.Now().Before(pollEndTime) {
					resource, err = client.AccountResource(mcmsUserDeployer.accountAddress, mcmsUserDeployerAddress+"::mcms_user::UserData")
					if err != nil {
						time.Sleep(time.Second * 1)
						continue
					}
					logger.Debugw("Got resource", "resource", resource)
					break
				}
				require.NotNil(t, resource)
			}

			// First schedule the timelock operations
			scheduleTimelockOps := []TimelockOperation{
				{
					Target:       mcmsUserDeployer.accountAddress,
					ModuleName:   "mcms_user",
					FunctionName: "function_one",
					Data:         functionOneParamBytes,
				},
				{
					Target:       mcmsUserDeployer.accountAddress,
					ModuleName:   "mcms_user",
					FunctionName: "function_two",
					Data:         functionTwoParamBytes,
				},
			}
			// ZERO_HASH (32 bytes of zeros)
			predecessor := make([]byte, 32)
			salt := []byte{}
			delay := TEST_DELAY

			rootMetadata := RootMetadata{
				Role:                 role,
				ChainID:              chainIdBig,
				MultiSig:             mcmsAccount,
				PreOpCount:           getPreOpCount(),
				PostOpCount:          getPreOpCount() + 1, // We execute this all in one OP
				OverridePreviousRoot: false,
			}

			op := TimelockOpsToOp(scheduleTimelockOps, predecessor, salt, delay, role, chainIdBig, mcmsAccount, getNextNonce)

			merkleTree, err := GenerateMerkleTree([]Op{op}, rootMetadata)
			require.NoError(t, err)

			setRootId := EnqueueSetRoot(t, logger, merkleTree, txm, rootMetadata, proposerSigners, deployerAddress, deployerPublicKeyHex, mcmsAddress)
			WaitForTxmId(t, txm, setRootId, time.Second*30)

			proof := merkleTree.GetProof(1)

			// Calculate the hash of our single operation (for verification)
			opHash, err := HashOp(&op)
			require.NoError(t, err)
			logger.Debugw("Leaf hash for operation", "hash", hex.EncodeToString(opHash[:]))

			// Verify that the proof is valid for our operation
			require.True(t, merkleTree.VerifyProof(proof, opHash), "Failed to verify merkle proof for the batched operation")

			// Schedule all operations in a single execute call, passing the complete proof
			txId := ScheduleBatchOperationsAsDeployer(t, logger, txm, mcmsAccount, deployerAddress, deployerPublicKeyHex,
				scheduleTimelockOps, predecessor, salt, delay, role, chainIdBig, op.Nonce, proof, true)
			WaitForTxmId(t, txm, txId, time.Second*30)

			for {
				queueLen, unconfirmedLen := txm.InflightCount()
				logger.Debugw("Inflight count", "queued", queueLen, "unconfirmed", unconfirmedLen)
				if queueLen == 0 && unconfirmedLen == 0 {
					break
				}
				time.Sleep(500 * time.Millisecond)
			}

			// Execute initial operations through timelock
			executeTimelockOps := []TimelockOperation{
				{
					Target:       mcmsUserDeployer.accountAddress,
					ModuleName:   "mcms_user",
					FunctionName: "function_one",
					Data:         functionOneParamBytes,
				},
				{
					Target:       mcmsUserDeployer.accountAddress,
					ModuleName:   "mcms_user",
					FunctionName: "function_two",
					Data:         functionTwoParamBytes,
				},
			}

			txId = ExecuteBatchOperations(t, txm, mcmsAddress, deployerAddress, deployerPublicKeyHex, executeTimelockOps, predecessor, salt, true)
			WaitForTxmId(t, txm, txId, time.Second*30)

			// check that user contract state was updated
			{
				pollEndTime := time.Now().Add(time.Second * 30)
				var resource map[string]any

				for time.Now().Before(pollEndTime) {
					resource, err = client.AccountResource(mcmsUserDeployer.accountAddress, mcmsUserDeployerAddress+"::mcms_user::UserData")
					if err != nil {
						time.Sleep(time.Second * 1)
						continue
					}
					logger.Debugw("Got resource", "resource", resource)
					break
				}
				require.NotNil(t, resource)

				var result struct {
					Data struct {
						Invocations int
						A           string
						B           string
						C           string
						D           string
					}
				}
				err = mapstructure.Decode(resource, &result)
				require.NoError(t, err)

				require.Equal(t, result.Data.A, functionOneArg1)

				bBytes, err := utils.DecodeHexRelaxed(result.Data.B)
				require.NoError(t, err)
				require.Equal(t, bBytes, functionOneArg2)

				cBytes, err := utils.DecodeHexRelaxed(result.Data.C)
				require.NoError(t, err)
				require.Equal(t, cBytes, functionTwoArg1)

				dInt, ok := new(big.Int).SetString(result.Data.D, 10)
				require.True(t, ok)
				require.Equal(t, dInt, functionTwoArg2)
			}
		})
	}

	t.Run("TestMCMSSetConfig", func(t *testing.T) {
		role := uint8(PROPOSER_ROLE)

		NUM_GROUPS := 32
		signerAddresses := [][]byte{}
		signerGroups := []uint8{}
		groupQuorums := make([]uint8, NUM_GROUPS)
		groupParents := make([]uint8, NUM_GROUPS)

		// Addresses are already sorted
		for _, signer := range proposerSigners {
			signerAddresses = append(signerAddresses, signer.Address)
			signerGroups = append(signerGroups, 0)
		}
		groupQuorums[0] = 2

		updateMinDelayData, err := bcs.SerializeSingle(func(ser *bcs.Serializer) {
			ser.U64(TEST_DELAY)
		})
		require.NoError(t, err)

		proposerMultisig := GetMultisigForRole(t, mcmsAddress, client, role)
		logger.Debugw("Proposer multisig", "multisig", proposerMultisig.String())

		paramValues := [][]byte{[]byte{role}}
		viewPayload := CreateViewPayload(mcmsAddress, "mcms", "get_config", []aptos.TypeTag{}, paramValues)
		data, err := client.View(viewPayload)
		require.NoError(t, err)
		logger.Debugw("Initial config data", "data", data)

		// Assert we have the correct number of signers
		configData := data[0].(map[string]interface{})
		configSigners := configData["signers"].([]interface{})
		require.Equal(t, len(proposerSigners), len(configSigners))

		// Now to call mcms::set_config, we must schedule through `mcms::schedule_batch`
		// We change config to remove a signer
		setConfigData, err := SerializeSetConfig(role, SignerConfig{
			// Remove the last signer
			Addresses:    signerAddresses[:len(signerAddresses)-1],
			Groups:       signerGroups[:len(signerGroups)-1],
			GroupQuorums: groupQuorums,
			GroupParents: groupParents,
		})
		require.NoError(t, err)

		scheduleTimelockOps := []TimelockOperation{
			{
				Target:       mcmsAccount,
				ModuleName:   "mcms",
				FunctionName: "timelock_update_min_delay",
				Data:         updateMinDelayData,
			},
			{
				Target:       mcmsAccount,
				ModuleName:   "mcms",
				FunctionName: "set_config",
				Data:         setConfigData,
			},
		}
		// ZERO_HASH (32 bytes of zeros)
		predecessor := make([]byte, 32)
		salt := []byte{}
		delay := TEST_DELAY

		rootMetadata := RootMetadata{
			Role:                 role,
			ChainID:              chainIdBig,
			MultiSig:             mcmsAccount,
			PreOpCount:           getPreOpCount(),
			PostOpCount:          getPreOpCount() + 1, // We execute this all in one OP
			OverridePreviousRoot: false,
		}
		op := TimelockOpsToOp(scheduleTimelockOps, predecessor, salt, delay, role, chainIdBig, mcmsAccount, getNextNonce)

		merkleTree, err := GenerateMerkleTree([]Op{op}, rootMetadata)
		require.NoError(t, err)

		setRootId := EnqueueSetRoot(t, logger, merkleTree, txm, rootMetadata, proposerSigners, deployerAddress, deployerPublicKeyHex, mcmsAddress)
		WaitForTxmId(t, txm, setRootId, time.Second*30)

		// The proper approach is to schedule all operations in a single execute call.
		// Since timelockOpsToOps now creates a single Op that contains all operations,
		// our merkle tree has just two leaves:
		//   - Index 0: Root metadata hash
		//   - Index 1: The single operation hash (containing all batched operations)

		// Get the complete proof for leaf index 1 (our single operation containing all operations)
		// This proof contains all sibling nodes needed to verify the path from leaf to root
		proof := merkleTree.GetProof(1)

		// Calculate the hash of our single operation (for verification)
		opHash, err := HashOp(&op)
		require.NoError(t, err)
		logger.Debugw("Leaf hash for operation", "hash", hex.EncodeToString(opHash[:]))

		// Verify that the proof is valid for our operation
		require.True(t, merkleTree.VerifyProof(proof, opHash), "Failed to verify merkle proof for the batched operation")

		// Schedule all operations in a single execute call, passing the complete proof
		txId := ScheduleBatchOperationsAsDeployer(t, logger, txm, mcmsAccount, deployerAddress, deployerPublicKeyHex,
			scheduleTimelockOps, predecessor, salt, delay, role, chainIdBig, op.Nonce, proof, true)
		WaitForTxmId(t, txm, txId, time.Second*30)

		// Wait for test delay
		time.Sleep(time.Duration(TEST_DELAY) * time.Second)

		// Execute all operations in a single batch transaction
		executeTimelockOps := []TimelockOperation{
			{
				Target:       mcmsAccount,
				ModuleName:   "mcms",
				FunctionName: "timelock_update_min_delay",
				Data:         updateMinDelayData,
			},
			{
				Target:       mcmsAccount,
				ModuleName:   "mcms",
				FunctionName: "set_config",
				Data:         setConfigData,
			},
		}

		// Execute all operations in a single batch call to execute_batch
		txId = ExecuteBatchOperations(t, txm, mcmsAddress, deployerAddress, deployerPublicKeyHex, executeTimelockOps, predecessor, salt, true)
		WaitForTxmId(t, txm, txId, time.Second*30)

		// Get number of signers after set_config to 2 signers (3 initially)
		postSetConfigData, postSetConfigErr := client.View(viewPayload)
		require.NoError(t, postSetConfigErr)

		// Assert that the removal of a signer was complete
		configData = postSetConfigData[0].(map[string]interface{})
		configSigners = configData["signers"].([]interface{})
		require.Equal(t, len(proposerSigners)-1, len(configSigners))
		logger.Debugw("postSetConfigData", "postSetConfigData", postSetConfigData)
	})
}

func compileMcmsContract(t *testing.T, packageAddress aptos.AccountAddress, ownerAddress aptos.AccountAddress) ([]byte, [][]byte) {
	compileResult := testutils.CompileMovePackage(t, filepath.Join("mcms", "mcms"), map[string]aptos.AccountAddress{
		"mcms":       packageAddress,
		"mcms_owner": ownerAddress,
	})

	return compileResult.PackageMetadata, compileResult.BytecodeModules
}

func compileMcmsUserContract(t *testing.T, packageAddress, mcmsAddress aptos.AccountAddress) ([]byte, []byte) {
	compileResult := testutils.CompileMovePackage(t, filepath.Join("mcms", "mcms_test"), map[string]aptos.AccountAddress{
		"mcms_test": packageAddress,
		"mcms":      mcmsAddress,
	})

	require.Equal(t, 1, len(compileResult.BytecodeModules))
	return compileResult.PackageMetadata, compileResult.BytecodeModules[0]
}

func TestGetProof(t *testing.T) {
	leaves := [][32]byte{
		crypto.Keccak256Hash([]byte("leaf1")),
		crypto.Keccak256Hash([]byte("leaf2")),
		crypto.Keccak256Hash([]byte("leaf3")),
		crypto.Keccak256Hash([]byte("leaf4")),
	}

	fmt.Printf("Leaves: %v\n", leaves)

	tree, err := NewMerkleTree(leaves)
	require.NoError(t, err)

	fmt.Printf("Tree: %v\n", tree)

	for i, leaf := range leaves {
		proof := tree.GetProof(i)

		fmt.Printf("Proof for leaf %d: %v\n", i, proof)

		// Verify the proof
		isValid := tree.VerifyProof(proof, leaf)
		require.True(t, isValid, "Proof should be valid for leaf %d", i)

		// Verify the proof manually
		computedHash := leaf
		for _, p := range proof {
			computedHash = HashPair(computedHash, p)
		}
		require.Equal(t, tree.GetRoot(), computedHash, "Computed root should match tree root for leaf %d", i)
	}
}

func broadcastPayload(t *testing.T, client *aptos.NodeClient, keystore loop.Keystore, fromAddress aptos.AccountAddress, publicKey ed25519.PublicKey, payload aptos.TransactionPayload) *aptosapi.SubmitTransactionResponse {
	chainId, err := client.GetChainId()
	require.NoError(t, err)

	nodeInfo, err := client.Info()
	require.NoError(t, err)

	ledgerTimestamp := nodeInfo.LedgerTimestamp()
	require.NotEqual(t, ledgerTimestamp, 0)

	accountInfo, err := client.Account(fromAddress)
	require.NoError(t, err)

	sequenceNumber, err := accountInfo.SequenceNumber()
	require.NoError(t, err)

	gasInfo, err := client.EstimateGasPrice()
	require.NoError(t, err)

	rawTx := aptos.RawTransaction{
		Sender:         fromAddress,
		SequenceNumber: sequenceNumber,
		Payload:        payload,
		MaxGasAmount:   200000,
		GasUnitPrice:   gasInfo.GasEstimate,
		// TODO: handle expiry
		ExpirationTimestampSeconds: ledgerTimestamp + uint64(600),
		ChainId:                    chainId,
	}

	signingMessage, err := rawTx.SigningMessage()
	require.NoError(t, err)

	signature, err := keystore.Sign(context.Background(), fmt.Sprintf("%064x", publicKey), signingMessage)
	require.NoError(t, err)

	aptosPublicKey := aptoscrypto.Ed25519PublicKey{}
	err = aptosPublicKey.FromBytes([]byte(publicKey))
	require.NoError(t, err)

	aptosSignature := aptoscrypto.Ed25519Signature{}
	err = aptosSignature.FromBytes(signature)
	require.NoError(t, err)

	authenticator := &aptoscrypto.Ed25519Authenticator{
		PubKey: &aptosPublicKey,
		Sig:    &aptosSignature,
	}

	signedTx, err := rawTx.SignedTransactionWithAuthenticator(&aptoscrypto.AccountAuthenticator{
		Variant: aptoscrypto.AccountAuthenticatorEd25519,
		Auth:    authenticator,
	})
	require.NoError(t, err)

	submitResponse, err := client.SubmitTransaction(signedTx)
	require.NoError(t, err)

	return submitResponse
}

// TODO: move these functions to testutils, and remove duplicates

func waitForTx(t *testing.T, client *aptos.NodeClient, txHash string, duration time.Duration) {
	stopTime := time.Now().Add(duration)
	for time.Now().Before(stopTime) {
		time.Sleep(time.Second * 1)
		txInfo, err := client.TransactionByHash(txHash)
		if err == nil && txInfo.Type != aptosapi.TransactionVariantPending {
			return
		}
	}
	t.Fatalf("Failed to wait for transaction %s", txHash)
}
