[package]
name = "MCMSRegistrar"
version = "1.0.0"
authors = []

[addresses]
link = "_"
mcms = "_"
mcms_register_entrypoints = "_"

[dev-addresses]
# Matches `@link` address in `link-token` package
link = "0xec027d053a48066c79c442d3215e1b775c47f832ac18f8e0539bbd6667f76e85"
mcms = "0x4001"
mcms_register_entrypoints = "0x9999"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "837d04bd9bd0dd7156da4252bcfc1d080ed591ec", subdir = "aptos-move/framework/aptos-framework" }
ChainlinkManyChainMultisig = { local = "../mcms/mcms", addr_subst = { 'mcms_owner' = '0x0' } }
ChainlinkToken = { local = "../link-token" }

[dev-dependencies]
