// Code generated by mockery v2.20.0. DO NOT EDIT.

package mock

import (
	aptos "github.com/aptos-labs/aptos-go-sdk"
	api "github.com/aptos-labs/aptos-go-sdk/api"

	mock "github.com/stretchr/testify/mock"
)

// RateLimitedClient is an autogenerated mock type for the RateLimitedClient type
type RateLimitedClient struct {
	mock.Mock
}

// Account provides a mock function with given fields: address
func (_m *RateLimitedClient) Account(address aptos.AccountAddress) (aptos.AccountInfo, error) {
	ret := _m.Called(address)

	var r0 aptos.AccountInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(aptos.AccountAddress) (aptos.AccountInfo, error)); ok {
		return rf(address)
	}
	if rf, ok := ret.Get(0).(func(aptos.AccountAddress) aptos.AccountInfo); ok {
		r0 = rf(address)
	} else {
		r0 = ret.Get(0).(aptos.AccountInfo)
	}

	if rf, ok := ret.Get(1).(func(aptos.AccountAddress) error); ok {
		r1 = rf(address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountAPTBalance provides a mock function with given fields: account, ledgerVersion
func (_m *RateLimitedClient) AccountAPTBalance(account aptos.AccountAddress, ledgerVersion ...uint64) (uint64, error) {
	_va := make([]interface{}, len(ledgerVersion))
	for _i := range ledgerVersion {
		_va[_i] = ledgerVersion[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, account)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(aptos.AccountAddress, ...uint64) (uint64, error)); ok {
		return rf(account, ledgerVersion...)
	}
	if rf, ok := ret.Get(0).(func(aptos.AccountAddress, ...uint64) uint64); ok {
		r0 = rf(account, ledgerVersion...)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(aptos.AccountAddress, ...uint64) error); ok {
		r1 = rf(account, ledgerVersion...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlockByHeight provides a mock function with given fields: height, withTransactions
func (_m *RateLimitedClient) BlockByHeight(height uint64, withTransactions bool) (*api.Block, error) {
	ret := _m.Called(height, withTransactions)

	var r0 *api.Block
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, bool) (*api.Block, error)); ok {
		return rf(height, withTransactions)
	}
	if rf, ok := ret.Get(0).(func(uint64, bool) *api.Block); ok {
		r0 = rf(height, withTransactions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Block)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, bool) error); ok {
		r1 = rf(height, withTransactions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EstimateGasPrice provides a mock function with given fields:
func (_m *RateLimitedClient) EstimateGasPrice() (aptos.EstimateGasInfo, error) {
	ret := _m.Called()

	var r0 aptos.EstimateGasInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() (aptos.EstimateGasInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() aptos.EstimateGasInfo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(aptos.EstimateGasInfo)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventsByHandle provides a mock function with given fields: address, eventHandle, fieldName, start, limit
func (_m *RateLimitedClient) EventsByHandle(address aptos.AccountAddress, eventHandle string, fieldName string, start *uint64, limit *uint64) ([]*api.Event, error) {
	ret := _m.Called(address, eventHandle, fieldName, start, limit)

	var r0 []*api.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(aptos.AccountAddress, string, string, *uint64, *uint64) ([]*api.Event, error)); ok {
		return rf(address, eventHandle, fieldName, start, limit)
	}
	if rf, ok := ret.Get(0).(func(aptos.AccountAddress, string, string, *uint64, *uint64) []*api.Event); ok {
		r0 = rf(address, eventHandle, fieldName, start, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*api.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(aptos.AccountAddress, string, string, *uint64, *uint64) error); ok {
		r1 = rf(address, eventHandle, fieldName, start, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChainId provides a mock function with given fields:
func (_m *RateLimitedClient) GetChainId() (uint8, error) {
	ret := _m.Called()

	var r0 uint8
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint8, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint8); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint8)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Info provides a mock function with given fields:
func (_m *RateLimitedClient) Info() (aptos.NodeInfo, error) {
	ret := _m.Called()

	var r0 aptos.NodeInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() (aptos.NodeInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() aptos.NodeInfo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(aptos.NodeInfo)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SimulateTransaction provides a mock function with given fields: rawTxn, sender, options
func (_m *RateLimitedClient) SimulateTransaction(rawTxn *aptos.RawTransaction, sender aptos.TransactionSigner, options ...interface{}) ([]*api.UserTransaction, error) {
	var _ca []interface{}
	_ca = append(_ca, rawTxn, sender)
	_ca = append(_ca, options...)
	ret := _m.Called(_ca...)

	var r0 []*api.UserTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*aptos.RawTransaction, aptos.TransactionSigner, ...interface{}) ([]*api.UserTransaction, error)); ok {
		return rf(rawTxn, sender, options...)
	}
	if rf, ok := ret.Get(0).(func(*aptos.RawTransaction, aptos.TransactionSigner, ...interface{}) []*api.UserTransaction); ok {
		r0 = rf(rawTxn, sender, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*api.UserTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*aptos.RawTransaction, aptos.TransactionSigner, ...interface{}) error); ok {
		r1 = rf(rawTxn, sender, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubmitTransaction provides a mock function with given fields: signedTxn
func (_m *RateLimitedClient) SubmitTransaction(signedTxn *aptos.SignedTransaction) (*api.PendingTransaction, error) {
	ret := _m.Called(signedTxn)

	var r0 *api.PendingTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*aptos.SignedTransaction) (*api.PendingTransaction, error)); ok {
		return rf(signedTxn)
	}
	if rf, ok := ret.Get(0).(func(*aptos.SignedTransaction) *api.PendingTransaction); ok {
		r0 = rf(signedTxn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.PendingTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*aptos.SignedTransaction) error); ok {
		r1 = rf(signedTxn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionByHash provides a mock function with given fields: hash
func (_m *RateLimitedClient) TransactionByHash(hash string) (*api.Transaction, error) {
	ret := _m.Called(hash)

	var r0 *api.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*api.Transaction, error)); ok {
		return rf(hash)
	}
	if rf, ok := ret.Get(0).(func(string) *api.Transaction); ok {
		r0 = rf(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// View provides a mock function with given fields: payload
func (_m *RateLimitedClient) View(payload *aptos.ViewPayload) ([]interface{}, error) {
	ret := _m.Called(payload)

	var r0 []interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(*aptos.ViewPayload) ([]interface{}, error)); ok {
		return rf(payload)
	}
	if rf, ok := ret.Get(0).(func(*aptos.ViewPayload) []interface{}); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(*aptos.ViewPayload) error); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRateLimitedClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewRateLimitedClient creates a new instance of RateLimitedClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRateLimitedClient(t mockConstructorTestingTNewRateLimitedClient) *RateLimitedClient {
	mock := &RateLimitedClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
