[package]
name = "ChainlinkManyChainMultisig"
version = "1.0.0"
authors = []

[addresses]
mcms = "_"
owner = "_"

[dev-addresses]
mcms = "0x100"
owner = "0x101"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
