syntax="proto3";

package data_feeds.on_chain.registry;
option go_package = ".;registry";

// The on-chain FeedUpdated event which is extracted from the tx/event data or
// the write-target WriteConfirmed event, after a write was confirmed (@see message: write-target.WriteConfirmed).
message FeedUpdated {
  bytes feed_id = 1;
  uint32 observations_timestamp = 2;
  // TODO: how to represent benchmark data which is u256 on-chain?
  uint64 benchmark = 3;

  bytes report = 4;

  // TODO: Transaction data - tx that mained the event (e.g., hash, gas, transmitter, payload, etc.)

  // Head data - when was the event produced on-chain
  string block_hash = 9;
  string block_height = 10;
  uint64 block_timestamp = 11;
}
