// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.4
// source: feed_updated.proto

package registry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The on-chain FeedUpdated event which is extracted (via Benthos) from the
// Keystone Forwarder contract transaction receipt after a write was confirmed
// (@see message: write-target.WriteConfirmed).
//
// Notice: contains chain specific metadata type as raw bytes
type FeedUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FeedId []byte `protobuf:"bytes,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	// TODO: Should we use "google/protobuf/timestamp.proto" for timestamps?
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Benchmark uint64 `protobuf:"varint,3,opt,name=benchmark,proto3" json:"benchmark,omitempty"`
	Report    []byte `protobuf:"bytes,4,opt,name=report,proto3" json:"report,omitempty"`
	Success   bool   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	// Metadata is a serialized protobuf message
	// For example, Aptos specific type hosting transaction data
	//
	//	(e.g., _metadata_type = "aptos-tx-metadata")
	XMetadata     []byte `protobuf:"bytes,6,opt,name=_metadata,json=Metadata,proto3" json:"_metadata,omitempty"`
	XMetadataType string `protobuf:"bytes,7,opt,name=_metadata_type,json=MetadataType,proto3" json:"_metadata_type,omitempty"`
}

func (x *FeedUpdated) Reset() {
	*x = FeedUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_updated_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedUpdated) ProtoMessage() {}

func (x *FeedUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_feed_updated_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedUpdated.ProtoReflect.Descriptor instead.
func (*FeedUpdated) Descriptor() ([]byte, []int) {
	return file_feed_updated_proto_rawDescGZIP(), []int{0}
}

func (x *FeedUpdated) GetFeedId() []byte {
	if x != nil {
		return x.FeedId
	}
	return nil
}

func (x *FeedUpdated) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FeedUpdated) GetBenchmark() uint64 {
	if x != nil {
		return x.Benchmark
	}
	return 0
}

func (x *FeedUpdated) GetReport() []byte {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *FeedUpdated) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FeedUpdated) GetXMetadata() []byte {
	if x != nil {
		return x.XMetadata
	}
	return nil
}

func (x *FeedUpdated) GetXMetadataType() string {
	if x != nil {
		return x.XMetadataType
	}
	return ""
}

var File_feed_updated_proto protoreflect.FileDescriptor

var file_feed_updated_proto_rawDesc = []byte{
	0x0a, 0x12, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x22, 0xd7,
	0x01, 0x0a, 0x0b, 0x46, 0x65, 0x65, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x66, 0x65, 0x65, 0x64, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x65, 0x6e, 0x63, 0x68, 0x6d, 0x61,
	0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x62, 0x65, 0x6e, 0x63, 0x68, 0x6d,
	0x61, 0x72, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x24, 0x0a, 0x0e, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_feed_updated_proto_rawDescOnce sync.Once
	file_feed_updated_proto_rawDescData = file_feed_updated_proto_rawDesc
)

func file_feed_updated_proto_rawDescGZIP() []byte {
	file_feed_updated_proto_rawDescOnce.Do(func() {
		file_feed_updated_proto_rawDescData = protoimpl.X.CompressGZIP(file_feed_updated_proto_rawDescData)
	})
	return file_feed_updated_proto_rawDescData
}

var file_feed_updated_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_feed_updated_proto_goTypes = []any{
	(*FeedUpdated)(nil), // 0: registry.FeedUpdated
}
var file_feed_updated_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_feed_updated_proto_init() }
func file_feed_updated_proto_init() {
	if File_feed_updated_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_feed_updated_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FeedUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_feed_updated_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feed_updated_proto_goTypes,
		DependencyIndexes: file_feed_updated_proto_depIdxs,
		MessageInfos:      file_feed_updated_proto_msgTypes,
	}.Build()
	File_feed_updated_proto = out.File
	file_feed_updated_proto_rawDesc = nil
	file_feed_updated_proto_goTypes = nil
	file_feed_updated_proto_depIdxs = nil
}
