[Log]
Level = 'debug'

[Feature]
FeedsManager = true
LogPoller = true
UICSAKeys = true

[OCR2]
Enabled = true

[P2P]
[P2P.V2]
Enabled = true
DeltaDial = '5s'
DeltaReconcile = '5s'
ListenAddresses = ['0.0.0.0:6690']

[WebServer]
HTTPPort = 6688
TLS.HTTPSPort = 0
AllowOrigins = '*'

[[Aptos]]
Enabled = true
ChainID = "4"
NetworkName = "localnet" # optional
NetworkNameFull = "aptos-localnet" # optional, CLL naming convention

[Aptos.Workflow]
ForwarderAddress = ""
PublicKey = ""

[[Aptos.Nodes]]
Name = 'primary'
URL = "http://chainlink-aptos.devnet:8080/v1"

[Aptos.BalanceMonitor]
BalancePollPeriod = '10s'

# TODO: migrate config types as time.Duration ('10s') instead of number (10)
# TODO: missing configs are not merged with defaults: https://smartcontract-it.atlassian.net/browse/NONEVM-810
[Aptos.TransactionManager]
BroadcastChanSize = 100
ConfirmPollSecs = 2
DefaultMaxGasAmount = 200000
MaxSimulateAttempts = 5
MaxSubmitRetryAttempts = 10
SubmitDelayDuration = 3      # seconds
TxExpirationSecs = 10        # seconds
MaxTxRetryAttempts = 5
PruneIntervalSecs = 14400    # 60 * 60 * 4 = 4 hours
PruneTxExpirationSecs = 7200 # 60 * 60 * 2 = 2 hours

[Aptos.WriteTargetCap]
ConfirmerPollPeriod = '300ms'
ConfirmerTimeout = '10s'

[[EVM]]
ChainID = '1337'
MinContractPayment = '0'
Enabled = true
Nodes = [{ Name = 'node-geth-0', WSURL = 'ws://chainlink.geth:8546', HTTPURL = 'http://chainlink.geth:8544' }]
