[Log]
Level = 'debug'

[Feature]
FeedsManager = true
LogPoller = true
UICSAKeys = true

[Capabilities.Local]
[Capabilities.Local.Capabilities."mock-streams-trigger@1.0.0"]

[OCR2]
Enabled = true

[P2P]
[P2P.V2]
Enabled = true
DeltaDial = '5s'
DeltaReconcile = '5s'
ListenAddresses = ['0.0.0.0:6690']

[WebServer]
HTTPPort = 6688
TLS.HTTPSPort = 0
AllowOrigins = '*'

[[Aptos]]
Enabled = true
ChainID = "4"
NetworkName = "localnet" # optional
NetworkNameFull = "aptos-localnet" # optional, CLL naming convention

[Aptos.Workflow]
ForwarderAddress = ""
PublicKey = ""

[[Aptos.Nodes]]
Name = 'primary'
URL = "http://chainlink-aptos.devnet:8080/v1"
MaxConcurrentRequests = 500
Timeout = '30s'

[Aptos.BalanceMonitor]
BalancePollPeriod = '10s'

[Aptos.TransactionManager]
BroadcastChanSize = 100
ConfirmPollInterval = '2s'
DefaultMaxGasAmount = 200000
MaxSimulateAttempts = 5
MaxSubmitRetryAttempts = 10
SubmitRetryDelay = '3s'
TxExpirationTimeout = '10s'
MaxTxRetryAttempts = 5
PruneInterval = '4h'
PruneTxExpiration = '2h'

[Aptos.WriteTargetCap]
ConfirmerPollPeriod = '300ms'
ConfirmerTimeout = '10s'

[Aptos.AptosService]
SubmitPollTimeout = '10s'
SimulateTx = true

[[EVM]]
ChainID = '1337'
MinContractPayment = '0'
Enabled = true
Nodes = [{ Name = 'node-geth-0', WSURL = 'ws://chainlink.geth:8546', HTTPURL = 'http://chainlink.geth:8544' }]
