[package]
name = "LargePackages"
version = "1.0.0"
upgrade_policy = "compatible"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "837d04bd9bd0dd7156da4252bcfc1d080ed591ec", subdir = "aptos-move/framework/aptos-framework" }

[addresses]
large_packages = "_"

[dev-addresses]
large_packages = "0x9000"
