syntax="proto3";

package write_target;
option go_package = ".;write_target";

message WriteAccepted {
  string forwarder = 1;
  string receiver = 2;
  string transmitter = 3;
  uint32 report_id = 4;

  bool success = 5;

  string tx_hash = 6;
  string block_hash = 7;
  uint64 block_num = 8;
  // TODO: Should we use "google/protobuf/timestamp.proto" for timestamps?
  uint64 block_timestamp = 9;

  // Metadata is a serialized protobuf message
  // For example, Aptos specific type hosting transaction data
  //   (e.g., _metadata_type = "aptos-tx-metadata")
  bytes _metadata = 10;
  string _metadata_type = 11;
}
