// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.4
// source: write_error.proto

package write_target

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Summary     string `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause       string `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	Forwarder   string `protobuf:"bytes,4,opt,name=forwarder,proto3" json:"forwarder,omitempty"`
	Receiver    string `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Transmitter string `protobuf:"bytes,6,opt,name=transmitter,proto3" json:"transmitter,omitempty"`
	ReportId    uint32 `protobuf:"varint,7,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	// Metadata is a serialized protobuf message
	// For example, Aptos specific type hosting API error data (e.g., _metadata_type = "aptos-api-error-metadata")
	XMetadata     []byte `protobuf:"bytes,8,opt,name=_metadata,json=Metadata,proto3" json:"_metadata,omitempty"`
	XMetadataType string `protobuf:"bytes,9,opt,name=_metadata_type,json=MetadataType,proto3" json:"_metadata_type,omitempty"`
}

func (x *WriteError) Reset() {
	*x = WriteError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_write_error_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteError) ProtoMessage() {}

func (x *WriteError) ProtoReflect() protoreflect.Message {
	mi := &file_write_error_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteError.ProtoReflect.Descriptor instead.
func (*WriteError) Descriptor() ([]byte, []int) {
	return file_write_error_proto_rawDescGZIP(), []int{0}
}

func (x *WriteError) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WriteError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *WriteError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *WriteError) GetForwarder() string {
	if x != nil {
		return x.Forwarder
	}
	return ""
}

func (x *WriteError) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *WriteError) GetTransmitter() string {
	if x != nil {
		return x.Transmitter
	}
	return ""
}

func (x *WriteError) GetReportId() uint32 {
	if x != nil {
		return x.ReportId
	}
	return 0
}

func (x *WriteError) GetXMetadata() []byte {
	if x != nil {
		return x.XMetadata
	}
	return nil
}

func (x *WriteError) GetXMetadataType() string {
	if x != nil {
		return x.XMetadataType
	}
	return ""
}

var File_write_error_proto protoreflect.FileDescriptor

var file_write_error_proto_rawDesc = []byte{
	0x0a, 0x11, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x22, 0x8c, 0x02, 0x0a, 0x0a, 0x57, 0x72, 0x69, 0x74, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x61, 0x75, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x20,
	0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72,
	0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x0e, 0x5f, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65,
	0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x3b, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_write_error_proto_rawDescOnce sync.Once
	file_write_error_proto_rawDescData = file_write_error_proto_rawDesc
)

func file_write_error_proto_rawDescGZIP() []byte {
	file_write_error_proto_rawDescOnce.Do(func() {
		file_write_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_write_error_proto_rawDescData)
	})
	return file_write_error_proto_rawDescData
}

var file_write_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_write_error_proto_goTypes = []any{
	(*WriteError)(nil), // 0: write_target.WriteError
}
var file_write_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_write_error_proto_init() }
func file_write_error_proto_init() {
	if File_write_error_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_write_error_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*WriteError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_write_error_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_write_error_proto_goTypes,
		DependencyIndexes: file_write_error_proto_depIdxs,
		MessageInfos:      file_write_error_proto_msgTypes,
	}.Build()
	File_write_error_proto = out.File
	file_write_error_proto_rawDesc = nil
	file_write_error_proto_goTypes = nil
	file_write_error_proto_depIdxs = nil
}
