[package]
name = "ChainlinkManyChainMultisig"
version = "1.0.0"
authors = []
upgrade_policy = "immutable"

[addresses]
mcms = "_"
mcms_owner = "_"

[dev-addresses]
# 0x248c47a86babdb39b73bf30fabb0af2f18beb4502722b31b8fb2250a0f5f0f06 must be the mcms address, as this is `multisig` address in the root metadata tests
mcms = "0x248c47a86babdb39b73bf30fabb0af2f18beb4502722b31b8fb2250a0f5f0f06"
mcms_owner = "0x4010"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "34025227eb5367c449bf9dae3cd226fe5c187904", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
