[package]
name = "ChainlinkCRECanaryReceiverPrimary"
version = "1.0.0"
authors = []

[addresses]
cre_canary_receiver_primary = "_"
platform = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "34025227eb5367c449bf9dae3cd226fe5c187904", subdir = "aptos-move/framework/aptos-framework" }
ChainlinkPlatform = { local = "../platform" }

[dev-addresses]
cre_canary_receiver_primary = "0x300"
platform = "0x100"
owner = "0xcafe"

[dev-dependencies]
