[package]
name = "RegulatedToken"
version = "1.0.0"
authors = []

[addresses]
regulated_token = "_"
admin = "_"

[dev-addresses]
# Calculated with object::create_named_object()
regulated_token = "0x121dfbc38157d675d96eef0bcc54e70e9801714138ce54028b5655459c6376ee"
admin = "0x456"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "837d04bd9bd0dd7156da4252bcfc1d080ed591ec", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
