// Integration tests for CurseMCMS calling into RMN Remote.
// These tests verify the complete curse flow: CurseMCMS -> dispatch -> RMN Remote.
#[test_only]
module curse_mcms::curse_mcms_integration_test {
    use std::account;
    use std::bcs;
    use std::object;
    use std::signer;
    use std::string;
    use aptos_framework::chain_id;
    use aptos_framework::timestamp;

    use ccip::auth;
    use ccip::rmn_remote;
    use ccip::state_object;

    use curse_mcms::curse_mcms;
    use curse_mcms::curse_mcms_account;

    // ================================================================
    // |                   Test Constants (from Go)                    |
    // ================================================================

    // Generated by: go test -v -run TestGenerateCurseMCMSTestData ./relayer/txm/
    // Using deterministic signers for reproducible tests

    const CHAIN_ID: u256 = 4;
    const VALID_UNTIL: u64 = 1893456000;
    const CHAIN_SELECTOR: u64 = 743186221051783445;

    // Contract Addresses (from Move.toml dev-addresses)
    // curse_mcms = 0xCCC

    // Signer Addresses (sorted, 20 bytes each) - derived from deterministic private keys
    const SIGNER_1: vector<u8> = x"2b5ad5c4795c026514f8317c7a215e218dccd6cf";
    const SIGNER_2: vector<u8> = x"6813eb9362372eef6200f3b1dbc3f819671cba69";
    const SIGNER_3: vector<u8> = x"7e5f4552091a69125d5dfcb7b8c2659029395bdf";

    // Root and Metadata - from Go test with target/module serialization
    const ROOT: vector<u8> = x"f2832465d278940e9f682f4b3e6f962e3e8aedd622fb6c0f838ff03f53908210";

    // Metadata Proof - from Go test
    const METADATA_PROOF: vector<vector<u8>> = vector[
        x"48cf83194da84532457da1822d140351bcbe0453ce3741c35c96d48eb0c307ba",
        x"ba1688951246ba6af3e584997757e6c8f5bbf92b3226a3b284e8c3ec30de39f7"
    ];

    // Signatures (2-of-3 quorum) - from Go test
    const SIGNATURES: vector<vector<u8>> = vector[
        x"861207b1108bb62885849ae42b8e658b0c45c71453b9f06bf00d3cef2278579411570f5b9c8b6f3883bf9dcd31685c48e979f8c37618fb4e7c14eac60a1e73811c",
        x"b360a7d14af2ae40b0130684e4d12019fa749e918d9392fcbe09b1223b1756d01179a33c7e1e422f69beb2fb0d0005f854f7bf7125e163eaa77ae19560288e981b"
    ];

    // All operations target curse_mcms module and timelock_bypasser_execute_batch function
    const TARGET_MODULE: vector<u8> = b"curse_mcms";
    const TARGET_FUNCTION: vector<u8> = b"timelock_bypasser_execute_batch";

    // Operation 1: curse via timelock_bypasser_execute_batch - from Go test with target/module serialization
    const OP1_NONCE: u64 = 0;
    const OP1_DATA: vector<u8> = x"0130b33dec3fcac5ef3ea775128d88722b64ba59a4598277e537f284917403df29010a726d6e5f72656d6f74650105637572736501111001000000000000000000000000000001";
    const OP1_PROOF: vector<vector<u8>> = vector[
        x"64bfab85ea2fb1f2f913a90b121fb9e4e15b5d48339e71df28e9a1017efca1ab",
        x"ba1688951246ba6af3e584997757e6c8f5bbf92b3226a3b284e8c3ec30de39f7"
    ];

    // Operation 2: uncurse via timelock_bypasser_execute_batch - from Go test
    const OP2_NONCE: u64 = 1;
    const OP2_DATA: vector<u8> = x"0130b33dec3fcac5ef3ea775128d88722b64ba59a4598277e537f284917403df29010a726d6e5f72656d6f74650107756e637572736501111001000000000000000000000000000001";
    const OP2_PROOF: vector<vector<u8>> = vector[
        x"2d6e282e59a8a30e32edbbdb6c0bdff283b0ae6cdc928233e4080a695354efd3",
        x"60e848956b6384ec8c20efad6f0f215e16a37f0f0b9eba3c5a3b8e001e179fd4"
    ];

    // Operation 3: curse_multiple via timelock_bypasser_execute_batch - from Go test
    const OP3_NONCE: u64 = 2;
    const OP3_DATA: vector<u8> = x"0130b33dec3fcac5ef3ea775128d88722b64ba59a4598277e537f284917403df29010a726d6e5f72656d6f7465010e63757273655f6d756c7469706c6501230210010000000000000000000000000000011001000000000000000000000000000002";
    const OP3_PROOF: vector<vector<u8>> = vector[
        x"4b8446f735ba7371febf2120680b5051b3e2cdce21867c3e68a104363e16d841",
        x"60e848956b6384ec8c20efad6f0f215e16a37f0f0b9eba3c5a3b8e001e179fd4"
    ];

    // Curse Subjects
    const GLOBAL_CURSE_SUBJECT: vector<u8> = x"01000000000000000000000000000001";
    const SUBJECT_2: vector<u8> = x"01000000000000000000000000000002";

    // Use BYPASSER_ROLE for testing (role 0)
    const BYPASSER_ROLE: u8 = 0;

    // Pre/Post op counts for the metadata
    const PRE_OP_COUNT: u64 = 0;
    const POST_OP_COUNT: u64 = 3;

    // ================================================================
    // |                     Test Setup Functions                      |
    // ================================================================

    /// Setup both CurseMCMS and RMN Remote for integration testing
    fun setup_integration(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        // Initialize timestamp and chain_id
        timestamp::set_time_has_started_for_testing(framework);
        timestamp::update_global_time_for_test_secs(1000);
        chain_id::initialize_for_test(framework, (CHAIN_ID as u8));

        // Create accounts
        account::create_account_for_test(signer::address_of(ccip));
        account::create_account_for_test(signer::address_of(ccip_owner));
        account::create_account_for_test(signer::address_of(curse_mcms_deployer));
        account::create_account_for_test(signer::address_of(curse_mcms_owner));

        // Initialize CCIP (use initialize_v1 to test legacy migration path)
        let _constructor_ref = object::create_named_object(ccip_owner, b"ccip");
        state_object::init_module_for_testing(ccip);
        auth::test_init_module(ccip);
        rmn_remote::initialize_v1(ccip_owner, CHAIN_SELECTOR);

        // Initialize CurseMCMS account (ownership) - stores at @curse_mcms
        curse_mcms_account::init_module_for_testing(curse_mcms_deployer);

        // Initialize CurseMCMS (multisigs)
        curse_mcms::init_module_for_testing(curse_mcms_deployer);
    }

    /// Setup CurseMCMS as an allowed curser in RMN Remote
    fun setup_curse_mcms_as_allowed_curser(ccip_owner: &signer) {
        // Get CurseMCMS account signer address (used by timelock dispatch)
        let curse_mcms_signer_addr = curse_mcms_account::get_address();

        // Initialize AllowedCursersV2 with CurseMCMS address
        rmn_remote::initialize_allowed_cursers_v2(
            ccip_owner, vector[curse_mcms_signer_addr]
        );
    }

    /// Setup CurseMCMS config with test signers
    fun setup_curse_mcms_config(curse_mcms_owner: &signer) {
        let signer_addresses = vector[SIGNER_1, SIGNER_2, SIGNER_3];
        let signer_groups = vector[0u8, 0u8, 0u8];
        let group_quorums = vector[
            2u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0
        ];
        let group_parents = vector[
            0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0
        ];

        curse_mcms::set_config(
            curse_mcms_owner,
            BYPASSER_ROLE,
            signer_addresses,
            signer_groups,
            group_quorums,
            group_parents,
            false
        );
    }

    // ================================================================
    // |          Option A: Direct Dispatch Integration Tests          |
    // ================================================================
    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_dispatch_curse_success(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );
        setup_curse_mcms_as_allowed_curser(ccip_owner);

        // Verify subject is not cursed initially
        assert!(!rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 0);

        // Execute curse via CurseMCMS timelock dispatch
        curse_mcms::test_timelock_dispatch_to_rmn_remote(
            string::utf8(b"curse"), bcs::to_bytes(&GLOBAL_CURSE_SUBJECT)
        );

        // Verify subject is now cursed
        assert!(rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 1);
    }

    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_dispatch_uncurse_success(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );
        setup_curse_mcms_as_allowed_curser(ccip_owner);

        // First curse the subject
        rmn_remote::curse(ccip_owner, GLOBAL_CURSE_SUBJECT);
        assert!(rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 0);

        // Execute uncurse via CurseMCMS timelock dispatch
        curse_mcms::test_timelock_dispatch_to_rmn_remote(
            string::utf8(b"uncurse"), bcs::to_bytes(&GLOBAL_CURSE_SUBJECT)
        );

        // Verify subject is now uncursed
        assert!(!rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 1);
    }

    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_dispatch_curse_multiple_success(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );
        setup_curse_mcms_as_allowed_curser(ccip_owner);

        // Verify subjects are not cursed initially
        assert!(!rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 0);
        assert!(!rmn_remote::is_cursed(SUBJECT_2), 1);

        // Execute curse_multiple via CurseMCMS timelock dispatch
        let subjects = vector[GLOBAL_CURSE_SUBJECT, SUBJECT_2];
        curse_mcms::test_timelock_dispatch_to_rmn_remote(
            string::utf8(b"curse_multiple"), bcs::to_bytes(&subjects)
        );

        // Verify both subjects are now cursed
        assert!(rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 2);
        assert!(rmn_remote::is_cursed(SUBJECT_2), 3);
    }

    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_dispatch_uncurse_multiple_success(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );
        setup_curse_mcms_as_allowed_curser(ccip_owner);

        // First curse both subjects
        rmn_remote::curse_multiple(ccip_owner, vector[GLOBAL_CURSE_SUBJECT, SUBJECT_2]);
        assert!(rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 0);
        assert!(rmn_remote::is_cursed(SUBJECT_2), 1);

        // Execute uncurse_multiple via CurseMCMS timelock dispatch
        let subjects = vector[GLOBAL_CURSE_SUBJECT, SUBJECT_2];
        curse_mcms::test_timelock_dispatch_to_rmn_remote(
            string::utf8(b"uncurse_multiple"), bcs::to_bytes(&subjects)
        );

        // Verify both subjects are now uncursed
        assert!(!rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 2);
        assert!(!rmn_remote::is_cursed(SUBJECT_2), 3);
    }

    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    #[
        expected_failure(
            abort_code = curse_mcms::curse_mcms::E_UNKNOWN_CURSE_MCMS_FUNCTION,
            location = curse_mcms::curse_mcms
        )
    ]
    fun test_dispatch_invalid_function_rejected(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );
        setup_curse_mcms_as_allowed_curser(ccip_owner);

        // Try to execute an invalid function - should fail with E_UNKNOWN_CURSE_MCMS_FUNCTION
        curse_mcms::test_timelock_dispatch_to_rmn_remote(
            string::utf8(b"set_config"), vector[]
        );
    }

    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    // 327699 = error::permission_denied(E_NOT_OWNER_OR_ALLOWED_CURSER)
    // = (5 << 16) | 19 = 0x50013
    #[expected_failure(abort_code = 327699, location = ccip::rmn_remote)]
    fun test_dispatch_without_allowed_curser_fails(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );

        // Initialize AllowedCursersV2 but DON'T add CurseMCMS as allowed curser
        rmn_remote::initialize_allowed_cursers_v2(ccip_owner, vector[]);

        // CurseMCMS tries to curse but is not authorized
        // Should fail with E_NOT_OWNER_OR_ALLOWED_CURSER (19)
        curse_mcms::test_timelock_dispatch_to_rmn_remote(
            string::utf8(b"curse"), bcs::to_bytes(&GLOBAL_CURSE_SUBJECT)
        );
    }

    // ================================================================
    // |                   CurseMCMS Signer Verification               |
    // ================================================================
    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_curse_mcms_signer_is_allowed_curser(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );

        // Get CurseMCMS account signer address (used by timelock dispatch)
        let curse_mcms_signer_addr = curse_mcms_account::get_address();

        // Add curse_mcms to allowed cursers
        rmn_remote::initialize_allowed_cursers_v2(
            ccip_owner, vector[curse_mcms_signer_addr]
        );

        // Verify curse_mcms is allowed
        assert!(rmn_remote::is_allowed_curser(curse_mcms_signer_addr), 0);

        // Verify other addresses are not allowed
        assert!(!rmn_remote::is_allowed_curser(@0x123), 1);
    }

    // ================================================================
    // |          Bypasser Execute Batch Integration Tests             |
    // ================================================================
    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_bypasser_execute_batch_curse(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );
        setup_curse_mcms_as_allowed_curser(ccip_owner);

        // Verify subject is not cursed initially
        assert!(!rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 0);

        // Execute bypasser execute batch with curse (targets rmn_remote on ccip)
        let targets = vector[@ccip];
        let module_names = vector[string::utf8(b"rmn_remote")];
        let function_names = vector[string::utf8(b"curse")];
        let datas = vector[bcs::to_bytes(&GLOBAL_CURSE_SUBJECT)];

        curse_mcms::test_timelock_bypasser_execute_batch(
            targets,
            module_names,
            function_names,
            datas
        );

        // Verify subject is now cursed
        assert!(rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 1);
    }

    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_bypasser_execute_batch_multiple_calls(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );
        setup_curse_mcms_as_allowed_curser(ccip_owner);

        // Verify subjects are not cursed initially
        assert!(!rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 0);
        assert!(!rmn_remote::is_cursed(SUBJECT_2), 1);

        // Execute bypasser execute batch with two curse operations (targets rmn_remote on ccip)
        let targets = vector[@ccip, @ccip];
        let module_names = vector[string::utf8(b"rmn_remote"), string::utf8(b"rmn_remote")];
        let function_names = vector[string::utf8(b"curse"), string::utf8(b"curse")];
        let datas = vector[bcs::to_bytes(&GLOBAL_CURSE_SUBJECT), bcs::to_bytes(&SUBJECT_2)];

        curse_mcms::test_timelock_bypasser_execute_batch(
            targets,
            module_names,
            function_names,
            datas
        );

        // Verify both subjects are now cursed
        assert!(rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 2);
        assert!(rmn_remote::is_cursed(SUBJECT_2), 3);
    }

    // ================================================================
    // |              Timelock Schedule and Execute Tests              |
    // ================================================================
    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_schedule_and_execute_batch_curse(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );
        setup_curse_mcms_as_allowed_curser(ccip_owner);

        // Verify subject is not cursed initially
        assert!(!rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 0);

        // Schedule a batch with delay 0 (since min_delay is 0)
        let targets = vector[@ccip];
        let module_names = vector[string::utf8(b"rmn_remote")];
        let function_names = vector[string::utf8(b"curse")];
        let datas = vector[bcs::to_bytes(&GLOBAL_CURSE_SUBJECT)];
        let predecessor = curse_mcms::zero_hash();
        let salt = x"0000000000000000000000000000000000000000000000000000000000000001";

        curse_mcms::test_timelock_schedule_batch(
            targets,
            module_names,
            function_names,
            datas,
            predecessor,
            salt,
            0 // delay
        );

        // Get the operation ID
        let calls = curse_mcms::create_calls(targets, module_names, function_names, datas);
        let id = curse_mcms::hash_operation_batch(calls, predecessor, salt);

        // Verify operation is ready (delay is 0)
        assert!(curse_mcms::timelock_is_operation_ready(id), 1);

        // Execute the batch
        curse_mcms::timelock_execute_batch(
            targets,
            module_names,
            function_names,
            datas,
            predecessor,
            salt
        );

        // Verify subject is now cursed
        assert!(rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 2);

        // Verify operation is done
        assert!(curse_mcms::timelock_is_operation_done(id), 3);
    }

    // ================================================================
    // |                    Timelock Min Delay Tests                   |
    // ================================================================
    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_timelock_min_delay_is_zero(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );

        // Verify min_delay is initialized to 0
        assert!(curse_mcms::timelock_min_delay() == 0, 0);
    }

    // ================================================================
    // |                     Function Blocking Tests                   |
    // ================================================================
    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_block_and_unblock_function(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );

        // Initially no functions are blocked
        assert!(curse_mcms::timelock_get_blocked_functions_count() == 0, 0);

        // Block a function
        curse_mcms::test_timelock_block_function(
            @ccip, string::utf8(b"rmn_remote"), string::utf8(b"curse")
        );

        // Verify function is blocked
        assert!(curse_mcms::timelock_get_blocked_functions_count() == 1, 1);

        // Unblock the function
        curse_mcms::test_timelock_unblock_function(
            @ccip, string::utf8(b"rmn_remote"), string::utf8(b"curse")
        );

        // Verify function is unblocked
        assert!(curse_mcms::timelock_get_blocked_functions_count() == 0, 2);
    }

    // ================================================================
    // |        E2E Tests with Merkle Proofs and Signatures            |
    // ================================================================
    // These tests verify the full MCMS flow:
    // 1. set_config - configure signers
    // 2. set_root - commit merkle root with signatures
    // 3. execute - execute operations with merkle proofs
    //
    // Note: set_root and execute are permissionless entry functions.
    // The signatures provide authorization, not the signer.
    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_e2e_set_root_and_execute_curse(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );
        setup_curse_mcms_as_allowed_curser(ccip_owner);
        setup_curse_mcms_config(curse_mcms_owner);

        // Verify subject is not cursed initially
        assert!(!rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 0);

        // Set root with signatures (commits the merkle tree)
        // set_root(role, root, valid_until, chain_id, multisig_addr,
        //          pre_op_count, post_op_count, override_previous_root,
        //          metadata_proof, signatures)
        curse_mcms::set_root(
            BYPASSER_ROLE,
            ROOT,
            VALID_UNTIL,
            CHAIN_ID,
            @curse_mcms,
            PRE_OP_COUNT,
            POST_OP_COUNT,
            false,
            METADATA_PROOF,
            SIGNATURES
        );

        // Execute operation 1: curse via timelock_bypasser_execute_batch
        // execute(role, chain_id, multisig_addr, nonce, to, module_name, function_name, data, proof)
        curse_mcms::execute(
            BYPASSER_ROLE,
            CHAIN_ID,
            @curse_mcms,
            OP1_NONCE,
            @curse_mcms, // Target is curse_mcms itself
            string::utf8(TARGET_MODULE),
            string::utf8(TARGET_FUNCTION),
            OP1_DATA,
            OP1_PROOF
        );

        // Verify subject is now cursed
        assert!(rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 1);
    }

    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_e2e_set_root_and_execute_curse_then_uncurse(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );
        setup_curse_mcms_as_allowed_curser(ccip_owner);
        setup_curse_mcms_config(curse_mcms_owner);

        // Verify subject is not cursed initially
        assert!(!rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 0);

        // Set root with signatures
        curse_mcms::set_root(
            BYPASSER_ROLE,
            ROOT,
            VALID_UNTIL,
            CHAIN_ID,
            @curse_mcms,
            PRE_OP_COUNT,
            POST_OP_COUNT,
            false,
            METADATA_PROOF,
            SIGNATURES
        );

        // Execute operation 1: curse via timelock_bypasser_execute_batch
        curse_mcms::execute(
            BYPASSER_ROLE,
            CHAIN_ID,
            @curse_mcms,
            OP1_NONCE,
            @curse_mcms,
            string::utf8(TARGET_MODULE),
            string::utf8(TARGET_FUNCTION),
            OP1_DATA,
            OP1_PROOF
        );

        // Verify subject is cursed
        assert!(rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 1);

        // Execute operation 2: uncurse via timelock_bypasser_execute_batch
        curse_mcms::execute(
            BYPASSER_ROLE,
            CHAIN_ID,
            @curse_mcms,
            OP2_NONCE,
            @curse_mcms,
            string::utf8(TARGET_MODULE),
            string::utf8(TARGET_FUNCTION),
            OP2_DATA,
            OP2_PROOF
        );

        // Verify subject is now uncursed
        assert!(!rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 2);
    }

    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_e2e_set_root_and_execute_curse_multiple(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );
        setup_curse_mcms_as_allowed_curser(ccip_owner);
        setup_curse_mcms_config(curse_mcms_owner);

        // Verify subjects are not cursed initially
        assert!(!rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 0);
        assert!(!rmn_remote::is_cursed(SUBJECT_2), 1);

        // Set root with signatures
        curse_mcms::set_root(
            BYPASSER_ROLE,
            ROOT,
            VALID_UNTIL,
            CHAIN_ID,
            @curse_mcms,
            PRE_OP_COUNT,
            POST_OP_COUNT,
            false,
            METADATA_PROOF,
            SIGNATURES
        );

        // Execute operation 1 and 2 first (need to execute in order)
        curse_mcms::execute(
            BYPASSER_ROLE,
            CHAIN_ID,
            @curse_mcms,
            OP1_NONCE,
            @curse_mcms,
            string::utf8(TARGET_MODULE),
            string::utf8(TARGET_FUNCTION),
            OP1_DATA,
            OP1_PROOF
        );

        curse_mcms::execute(
            BYPASSER_ROLE,
            CHAIN_ID,
            @curse_mcms,
            OP2_NONCE,
            @curse_mcms,
            string::utf8(TARGET_MODULE),
            string::utf8(TARGET_FUNCTION),
            OP2_DATA,
            OP2_PROOF
        );

        // Uncurse first subject to reset state
        assert!(!rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 2);

        // Execute operation 3: curse_multiple
        curse_mcms::execute(
            BYPASSER_ROLE,
            CHAIN_ID,
            @curse_mcms,
            OP3_NONCE,
            @curse_mcms,
            string::utf8(TARGET_MODULE),
            string::utf8(TARGET_FUNCTION),
            OP3_DATA,
            OP3_PROOF
        );

        // Verify both subjects are now cursed
        assert!(rmn_remote::is_cursed(GLOBAL_CURSE_SUBJECT), 3);
        assert!(rmn_remote::is_cursed(SUBJECT_2), 4);
    }

    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    #[
        expected_failure(
            abort_code = curse_mcms::curse_mcms::E_POST_OP_COUNT_REACHED,
            location = curse_mcms::curse_mcms
        )
    ]
    fun test_e2e_execute_fails_without_set_root(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );
        setup_curse_mcms_as_allowed_curser(ccip_owner);
        setup_curse_mcms_config(curse_mcms_owner);

        // Try to execute without setting root first - should fail
        curse_mcms::execute(
            BYPASSER_ROLE,
            CHAIN_ID,
            @curse_mcms,
            OP1_NONCE,
            @curse_mcms,
            string::utf8(TARGET_MODULE),
            string::utf8(TARGET_FUNCTION),
            OP1_DATA,
            OP1_PROOF
        );
    }

    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    #[
        expected_failure(
            abort_code = curse_mcms::curse_mcms::E_PROOF_CANNOT_BE_VERIFIED,
            location = curse_mcms::curse_mcms
        )
    ]
    fun test_e2e_execute_fails_with_wrong_proof(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );
        setup_curse_mcms_as_allowed_curser(ccip_owner);
        setup_curse_mcms_config(curse_mcms_owner);

        // Set root
        curse_mcms::set_root(
            BYPASSER_ROLE,
            ROOT,
            VALID_UNTIL,
            CHAIN_ID,
            @curse_mcms,
            PRE_OP_COUNT,
            POST_OP_COUNT,
            false,
            METADATA_PROOF,
            SIGNATURES
        );

        // Try to execute with wrong proof - should fail with E_PROOF_CANNOT_BE_VERIFIED
        let wrong_proof = vector[
            x"0000000000000000000000000000000000000000000000000000000000000000",
            x"0000000000000000000000000000000000000000000000000000000000000000"
        ];
        curse_mcms::execute(
            BYPASSER_ROLE,
            CHAIN_ID,
            @curse_mcms,
            OP1_NONCE,
            @curse_mcms,
            string::utf8(TARGET_MODULE),
            string::utf8(TARGET_FUNCTION),
            OP1_DATA,
            wrong_proof
        );
    }

    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    #[
        expected_failure(
            abort_code = curse_mcms::curse_mcms::E_WRONG_NONCE,
            location = curse_mcms::curse_mcms
        )
    ]
    fun test_e2e_execute_fails_replay_attack(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );
        setup_curse_mcms_as_allowed_curser(ccip_owner);
        setup_curse_mcms_config(curse_mcms_owner);

        // Set root
        curse_mcms::set_root(
            BYPASSER_ROLE,
            ROOT,
            VALID_UNTIL,
            CHAIN_ID,
            @curse_mcms,
            PRE_OP_COUNT,
            POST_OP_COUNT,
            false,
            METADATA_PROOF,
            SIGNATURES
        );

        // Execute operation 1
        curse_mcms::execute(
            BYPASSER_ROLE,
            CHAIN_ID,
            @curse_mcms,
            OP1_NONCE,
            @curse_mcms,
            string::utf8(TARGET_MODULE),
            string::utf8(TARGET_FUNCTION),
            OP1_DATA,
            OP1_PROOF
        );

        // Try to replay the same operation - should fail with E_WRONG_NONCE
        curse_mcms::execute(
            BYPASSER_ROLE,
            CHAIN_ID,
            @curse_mcms,
            OP1_NONCE,
            @curse_mcms,
            string::utf8(TARGET_MODULE),
            string::utf8(TARGET_FUNCTION),
            OP1_DATA,
            OP1_PROOF
        );
    }

    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    #[
        expected_failure(
            abort_code = curse_mcms::curse_mcms::E_WRONG_NONCE,
            location = curse_mcms::curse_mcms
        )
    ]
    fun test_e2e_execute_fails_out_of_order(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );
        setup_curse_mcms_as_allowed_curser(ccip_owner);
        setup_curse_mcms_config(curse_mcms_owner);

        // Set root
        curse_mcms::set_root(
            BYPASSER_ROLE,
            ROOT,
            VALID_UNTIL,
            CHAIN_ID,
            @curse_mcms,
            PRE_OP_COUNT,
            POST_OP_COUNT,
            false,
            METADATA_PROOF,
            SIGNATURES
        );

        // Try to execute operation 2 before operation 1 - should fail with E_WRONG_NONCE
        curse_mcms::execute(
            BYPASSER_ROLE,
            CHAIN_ID,
            @curse_mcms,
            OP2_NONCE,
            @curse_mcms,
            string::utf8(TARGET_MODULE),
            string::utf8(TARGET_FUNCTION),
            OP2_DATA,
            OP2_PROOF
        );
    }

    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_e2e_view_functions_after_set_root(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );
        setup_curse_mcms_as_allowed_curser(ccip_owner);
        setup_curse_mcms_config(curse_mcms_owner);

        // Set root
        curse_mcms::set_root(
            BYPASSER_ROLE,
            ROOT,
            VALID_UNTIL,
            CHAIN_ID,
            @curse_mcms,
            PRE_OP_COUNT,
            POST_OP_COUNT,
            false,
            METADATA_PROOF,
            SIGNATURES
        );

        // Verify view functions - get_root returns (root, valid_until)
        let (root, valid_until) = curse_mcms::get_root(BYPASSER_ROLE);
        assert!(root == ROOT, 0);
        assert!(valid_until == VALID_UNTIL, 1);
        assert!(curse_mcms::get_op_count(BYPASSER_ROLE) == PRE_OP_COUNT, 2);

        // Execute one operation
        curse_mcms::execute(
            BYPASSER_ROLE,
            CHAIN_ID,
            @curse_mcms,
            OP1_NONCE,
            @curse_mcms,
            string::utf8(TARGET_MODULE),
            string::utf8(TARGET_FUNCTION),
            OP1_DATA,
            OP1_PROOF
        );

        // Verify op_count incremented
        assert!(curse_mcms::get_op_count(BYPASSER_ROLE) == 1, 3);
    }

    // ================================================================
    // |              Self-Dispatch Integration Tests                  |
    // ================================================================
    // These tests verify the timelock self-dispatch mechanism that allows
    // timelock admin functions to be called via bypasser_execute_batch
    // and schedule/execute flows.
    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_bypasser_execute_batch_timelock_update_min_delay(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );

        // Verify min_delay is initially 0
        assert!(curse_mcms::timelock_min_delay() == 0);

        // Execute bypasser execute batch with timelock_update_min_delay
        // This tests the self-dispatch path: bypasser_execute_batch -> timelock_dispatch -> dispatch_to_timelock
        let targets = vector[@curse_mcms];
        let module_names = vector[string::utf8(b"curse_mcms")];
        let function_names = vector[string::utf8(b"timelock_update_min_delay")];
        let new_delay: u64 = 3600; // 1 hour
        let datas = vector[bcs::to_bytes(&new_delay)];

        curse_mcms::test_timelock_bypasser_execute_batch(
            targets,
            module_names,
            function_names,
            datas
        );

        assert!(curse_mcms::timelock_min_delay() == 3600);
    }

    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_bypasser_execute_batch_timelock_block_function(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );

        // Verify no functions are blocked initially
        assert!(curse_mcms::timelock_get_blocked_functions_count() == 0);

        // Execute bypasser execute batch with timelock_block_function
        // Data: BCS-serialized (target: address, module_name: String, function_name: String)
        let targets = vector[@curse_mcms];
        let module_names = vector[string::utf8(b"curse_mcms")];
        let function_names = vector[string::utf8(b"timelock_block_function")];
        let block_data = bcs::to_bytes(&@ccip);
        block_data.append(bcs::to_bytes(&string::utf8(b"rmn_remote")));
        block_data.append(bcs::to_bytes(&string::utf8(b"curse")));
        let datas = vector[block_data];

        curse_mcms::test_timelock_bypasser_execute_batch(
            targets,
            module_names,
            function_names,
            datas
        );

        assert!(curse_mcms::timelock_get_blocked_functions_count() == 1);
    }

    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_bypasser_execute_batch_timelock_unblock_function(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );

        // First block a function directly
        curse_mcms::test_timelock_block_function(
            @ccip, string::utf8(b"rmn_remote"), string::utf8(b"curse")
        );
        assert!(curse_mcms::timelock_get_blocked_functions_count() == 1);

        // Execute bypasser execute batch with timelock_unblock_function
        // Data: BCS-serialized (target: address, module_name: String, function_name: String)
        let targets = vector[@curse_mcms];
        let module_names = vector[string::utf8(b"curse_mcms")];
        let function_names = vector[string::utf8(b"timelock_unblock_function")];
        let unblock_data = bcs::to_bytes(&@ccip);
        unblock_data.append(bcs::to_bytes(&string::utf8(b"rmn_remote")));
        unblock_data.append(bcs::to_bytes(&string::utf8(b"curse")));
        let datas = vector[unblock_data];

        curse_mcms::test_timelock_bypasser_execute_batch(
            targets,
            module_names,
            function_names,
            datas
        );

        assert!(curse_mcms::timelock_get_blocked_functions_count() == 0);
    }

    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_schedule_and_execute_batch_timelock_update_min_delay(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );

        // Verify min_delay is initially 0
        assert!(curse_mcms::timelock_min_delay() == 0);

        // Schedule a batch with timelock_update_min_delay
        let targets = vector[@curse_mcms];
        let module_names = vector[string::utf8(b"curse_mcms")];
        let function_names = vector[string::utf8(b"timelock_update_min_delay")];
        let new_delay: u64 = 7200; // 2 hours
        let datas = vector[bcs::to_bytes(&new_delay)];
        let predecessor = curse_mcms::zero_hash();
        let salt = x"0000000000000000000000000000000000000000000000000000000000000002";

        curse_mcms::test_timelock_schedule_batch(
            targets,
            module_names,
            function_names,
            datas,
            predecessor,
            salt,
            0 // delay (min_delay is 0)
        );

        // Get the operation ID
        let calls = curse_mcms::create_calls(targets, module_names, function_names, datas);
        let id = curse_mcms::hash_operation_batch(calls, predecessor, salt);

        // Verify operation is ready
        assert!(curse_mcms::timelock_is_operation_ready(id));

        // Execute the batch
        curse_mcms::timelock_execute_batch(
            targets,
            module_names,
            function_names,
            datas,
            predecessor,
            salt
        );

        // Verify min_delay was updated
        assert!(curse_mcms::timelock_min_delay() == 7200);

        // Verify operation is done
        assert!(curse_mcms::timelock_is_operation_done(id));
    }

    #[
        test(
            framework = @aptos_framework,
            ccip = @ccip,
            ccip_owner = @mcms,
            curse_mcms_deployer = @curse_mcms,
            curse_mcms_owner = @curse_mcms_owner
        )
    ]
    fun test_dispatch_to_self_directly(
        framework: &signer,
        ccip: &signer,
        ccip_owner: &signer,
        curse_mcms_deployer: &signer,
        curse_mcms_owner: &signer
    ) {
        setup_integration(
            framework,
            ccip,
            ccip_owner,
            curse_mcms_deployer,
            curse_mcms_owner
        );

        // Verify min_delay is initially 0
        assert!(curse_mcms::timelock_min_delay() == 0);

        // Call test_timelock_dispatch_to_self directly
        let new_delay: u64 = 1800; // 30 minutes
        curse_mcms::test_timelock_dispatch_to_self(
            string::utf8(b"timelock_update_min_delay"),
            bcs::to_bytes(&new_delay)
        );

        // Verify min_delay was updated
        assert!(curse_mcms::timelock_min_delay() == 1800);
    }
}
