name: 'Extract Go Version'
description: 'Extracts the Go version from the .tool-versions file and sets it as an environment variable.'
inputs:
  working-directory:
    description: 'The directory where the .tool-versions file is located.'
    required: true
    default: '.'

outputs:
  go_version:
    description: 'The extracted Go version.'
    value: ${{ steps.extract-go-version.outputs.go_version }}

runs:
  using: 'composite'
  steps:
    - name: Extract go version
      id: extract-go-version
      shell: bash
      env:
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
      run: |
          set -euo pipefail
          go_version=$(grep -E '^golang [0-9]+\.[0-9]+\.[0-9]+' ${WORKING_DIRECTORY}/.tool-versions | awk '{print $2}')
          echo "go_version=${go_version}" >> $GITHUB_ENV
          echo "go_version=${go_version}" | tee -a "${GITHUB_OUTPUT}"
