syntax="proto3";

package keystone.write_target;
option go_package = ".;write_target";

// WT confirmed the report was successfully written on-chain
message WriteConfirmed {
  string node = 1;
  string forwarder = 2;
  string receiver = 3;

  // Report Info
  uint32 report_id = 4;
  bytes report_context = 5;
  bytes report = 6;
  uint32 signers_num = 7;

  // Is the report finalized on-chain?
  bool finalized = 8;

  // When was the report confirmed on-chain
  string block_hash = 9;
  string block_height = 10;
  uint64 block_timestamp = 11;

  // Transmission Info
  string transmitter = 12;
  bool success = 13;
  // TODO: what about EVM's TransmissionInfo parity?
}
