[package]
name = "MCMSTokenRegistrar"
version = "1.0.0"
authors = []

[addresses]
link = "_"
mcms = "_"
mcms_register_entrypoints = "_"

[dev-addresses]
# Matches `@link` address in `link-token` package
link = "0x8e1c980369b736c76f18e37320e42ba8387afcec18e513e46ef46c7599c02787"
mcms = "0x4001"
mcms_register_entrypoints = "0x9999"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "837d04bd9bd0dd7156da4252bcfc1d080ed591ec", subdir = "aptos-move/framework/aptos-framework" }
ChainlinkManyChainMultisig = { local = "../mcms/mcms", addr_subst = { 'mcms_owner' = '0x0' } }
ChainlinkToken = { local = "../link-token" }

[dev-dependencies]
