[package]
name = "ChainlinkCCIPDummyReceiver"
version = "1.0.0"
authors = []

[addresses]
ccip = "_"
ccip_dummy_receiver = "_"
mcms = "_"
mcms_register_entrypoints = "_"

[dev-addresses]
ccip = "0x1000"
ccip_dummy_receiver = "0x3010"
mcms = "0x4000"
mcms_register_entrypoints = "0x4001"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "34025227eb5367c449bf9dae3cd226fe5c187904", subdir = "aptos-move/framework/aptos-framework" }
ChainlinkCCIP = { local = "../ccip" }

[dev-dependencies]
