[package]
name = "ChainlinkCCIP"
version = "1.0.0"
published-at = "0x0" # Will be updated with the actual ID after publication

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }
ChainlinkManyChainMultisig = { local = "../mcms" }

[addresses]
chainlink_ccip = "0x0"
