[package]
name = "ChainlinkCCIP"
version = "1.0.0"
authors = []

[addresses]
ccip = "_"

[dev-addresses]
ccip = "0x100"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
