[package]
name = "ChainlinkCCIP"
version = "1.0.0"
authors = []

[addresses]
ccip = "_"
mcms = "_"
# If set to 0x0, will not register mcms entrypoints
mcms_register_entrypoints = "_"

[dev-addresses]
## CCIP Core: 1xxx
ccip = "0x1000"

# MCMS: 4xxx
mcms = "0x4000"
mcms_register_entrypoints = "0x4001"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "837d04bd9bd0dd7156da4252bcfc1d080ed591ec", subdir = "aptos-move/framework/aptos-framework" }
ChainlinkManyChainMultisig = { local = "../../mcms/mcms", addr_subst = { 'mcms_owner' = '0x0' } }

[dev-dependencies]
