[package]
name = "TestModule"
version = "1.0.0"
authors = []

[addresses]
mcms_test = "_"
mcms = "_"

[dev-addresses]
mcms = "0x4000"
mcms_test = "0x4900"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "34025227eb5367c449bf9dae3cd226fe5c187904", subdir = "aptos-move/framework/aptos-framework" }
ChainlinkManyChainMultisig = { local = "../mcms", addr_subst = { 'mcms_owner' = '0x0' } }

