name: CCIP Integration Test

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    # edited is not one of the default events, re-run incase the core-ref was modified
    # in the PR body
    types: [opened, synchronize, reopened, edited]

concurrency:
  group: ccip-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ccip_test_evm2aptos:
    name: Run EVM2Aptos Test
    runs-on: ubuntu-latest
    env:
      DEFAULT_CORE_REF: develop
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DB_URL: postgresql://postgres:postgres@localhost:5432/chainlink_test?sslmode=disable
    steps:
      - name: Free up disk space
        uses: smartcontractkit/.github/actions/free-disk-space@free-disk-space/v1

      - name: Get core ref from PR body
        if: github.event_name == 'pull_request'
        run: |
          comment=$(gh pr view https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }} --json body -q '.body')
          core_ref=$(echo $comment | grep -oP 'core ref: \K\S+' || true)
          if [ ! -z "$core_ref" ]; then
            echo "CUSTOM_CORE_REF=${core_ref}" >> "${GITHUB_ENV}"
          fi

      - name: Install Aptos CLI
        uses: aptos-labs/actions/install-aptos-cli@528ef7ad9427a8c0720ea3eea790a9190d6e377d # 2026-04-09
        with:
          CLI_VERSION: 9.1.0

      - name: Checkout chainlink-aptos
        uses: actions/checkout@v6

      - name: Checkout chainlink
        uses: actions/checkout@v6
        with:
          repository: smartcontractkit/chainlink
          ref: ${{ env.CUSTOM_CORE_REF || env.DEFAULT_CORE_REF }}
          path: temp/chainlink

      - name: Read go version from core .tool-versions
        id: tool_versions
        run: |
          go_version=$(grep -E '^golang ' temp/chainlink/.tool-versions | cut -d' ' -f2)
          echo "GO_VERSION=${go_version}" >> "${GITHUB_OUTPUT}"

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ steps.tool_versions.outputs.GO_VERSION }}

      - name: Update chainlink-aptos sha
        env:
          COMMIT_SHA: ${{ github.event_name == 'push' && github.sha || github.event.pull_request.head.sha }}
        run: |
          cd temp/chainlink
          find . -name "go.mod" -exec sed -i -E "/.*\/chainlink-aptos \S+/ s/(.*\/chainlink-aptos) \S+/\1 ${COMMIT_SHA}/g" {} \;
          GIT_PAGER= git diff
          make gomodtidy

      - name: Build LOOP plugin
        run: |
          go build -o chainlink-aptos ./cmd/chainlink-aptos/main.go

      - name: Setup Postgres
        uses: smartcontractkit/.github/actions/setup-postgres@setup-postgres/v1
        with:
          tmpfs: "true"
          image-tag: "16-alpine"

      - name: Download Go vendor packages
        run: go mod download
        working-directory: temp/chainlink

      - name: Setup DB
        working-directory: temp/chainlink
        run: go run ./core/store/cmd/preparetest
        env:
          CL_DATABASE_URL: ${{ env.DB_URL }}

      - name: Run Test
        env:
          CL_DATABASE_URL: ${{ env.DB_URL }}
          CL_APTOS_CMD: ${{ github.workspace }}/chainlink-aptos
        run: |
          cd temp/chainlink/integration-tests/smoke/ccip
          go test -v -tags=integration -count=1 -timeout=30m -run Test_CCIP_Messaging_EVM2Aptos ./...
