name: Aptos - Check generated bindings
# This workflow checks that all generated bindings are up-to-date
on: [pull_request]
jobs:
  bindgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Aptos CLI
        uses: aptos-labs/actions/install-aptos-cli@ce57287eb852b9819c1d74fecc3be187677559fd # v0.1
        with:
          CLI_VERSION: 8.1.0
      - name: Run make wrappers
        run: make wrappers
      - name: Check if any files have been changed
        run: |
          if ! git diff --quiet HEAD; then
          	echo "The following bindings don't match the latest generated version, run \`go generate ./gen.go\` and commit your changes:" >> $GITHUB_STEP_SUMMARY
          	git diff --name-only | while read -r n ; do
          		echo "- $n" >> $GITHUB_STEP_SUMMARY
          	done
          	exit 1
          fi
      - name: Run go test
        run: go test ./bindings/...
