name: Aptos - Lint Move formatting
# This workflow checks that all move packages are correctly formatting using movefmt
on: [pull_request]
jobs:
  movefmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Aptos CLI
        uses: aptos-labs/actions/install-aptos-cli@ce57287eb852b9819c1d74fecc3be187677559fd # v0.1
        with:
          CLI_VERSION: 8.1.0
      - name: Update movefmt
        run: aptos update movefmt --target-version 1.4.9 # Fix version to prevent accidentally breaking the CI
      - name: Run movefmt
        run: make fmt
      - name: Check if any files have been changed
        run: |
          if ! git diff --quiet HEAD; then
          	echo "The following files don't have the required formatting applied, run \`movefmt\` to apply:" >> $GITHUB_STEP_SUMMARY
          	git diff --name-only | while read -r n ; do
          		echo "- $n" >> $GITHUB_STEP_SUMMARY
          	done
          	exit 1
          fi
