name: Go

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Linting Go
        uses: smartcontractkit/.github/actions/ci-lint-go@ci-lint-go/v4
        with:
          golangci-lint-version: v2.4.0
          golangci-lint-args: --timeout 5m
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Aptos CLI
        uses: aptos-labs/actions/install-aptos-cli@528ef7ad9427a8c0720ea3eea790a9190d6e377d # 2026-04-09
        with:
          CLI_VERSION: 9.1.0
      - name: Build and test
        uses: smartcontractkit/.github/actions/ci-test-go@ci-test-go/v1
        with:
          use-go-cache: true
  on-chain-data-test:
    name: On-chain Data Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Extract Go version
        uses: ./.github/actions/check-go-version

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.go_version }}
          cache-dependency-path: scripts/on-chain-data/go.sum

      - name: Run on-chain-data tests
        working-directory: scripts/on-chain-data
        run: go test -count=1 ./...
